-- =====================================================================
-- T1 : les 31 exercices restés à l'ancien format passent au format
-- structuré (étapes, points clés, erreurs, compétences, charges).
-- Contenu dérivé de leurs consignes existantes.
-- =====================================================================
update public.exercises e set
  slug                 = v.slug,
  category             = coalesce(e.category, v.category),
  skills               = v.skills,
  tags                 = v.tags,
  intensity            = v.intensity,
  physical_load        = v.physical_load,
  technical_load       = v.technical_load,
  solo_compatible      = v.solo_compatible,
  ball_required        = v.ball_required,
  players_min          = v.players_min,
  players_max          = v.players_max,
  instruction_steps    = v.instruction_steps,
  coaching_points      = v.coaching_points,
  common_mistakes_list = v.common_mistakes_list,
  progressions         = v.progressions,
  regressions          = v.regressions,
  objective_statement  = v.objective_statement
from (values
('91608839-23e9-44f3-b987-7ae1904ee4f4'::uuid,'attaque_201','attaque',
 array[$q$élan$q$,$q$timing$q$,$q$attaque de ligne$q$], array[$q$attaque$q$,$q$elan$q$,$q$ligne$q$,$q$timing$q$],
 'high',4,4,false,true,2,6,
 array[$q$Le passeur envoie une passe haute en zone 4.$q$,$q$L'attaquant enchaîne une approche en trois appuis et frappe en ligne droite.$q$,$q$4 séries de 8 attaques.$q$],
 array[$q$Synchronise ton dernier appui avec la montée du ballon.$q$,$q$Arme le bras dès la fin de la course, pas au moment du saut.$q$,$q$Frappe au point le plus haut, bras tendu.$q$],
 array[$q$Appel trop tôt ou trop tard par rapport à la passe.$q$,$q$Bras d'armé qui casse le rythme de l'approche.$q$],
 array[$q$Ajoute un bloqueur qui ferme la ligne.$q$], array[$q$Travaille l'approche sans ballon, puis avec ballon tenu en main.$q$],
 $q$Caler le rythme de l'approche et frapper en ligne.$q$),

('1f629cff-c08d-4b5f-a92b-8632ff367eeb','attaque_202','attaque',
 array[$q$attaque de ligne$q$,$q$élan$q$,$q$point de frappe haut$q$], array[$q$attaque$q$,$q$zone 2$q$,$q$pointu$q$,$q$elan$q$],
 'high',4,4,false,true,2,6,
 array[$q$Le passeur envoie une passe haute en zone 2.$q$,$q$Le pointu attaque en alternant longue ligne et croisé court.$q$,$q$4 séries de 8 attaques.$q$],
 array[$q$Recule ton point de départ d'un pas pour avoir plus d'élan.$q$,$q$Garde le ballon devant l'épaule de frappe.$q$,$q$Oriente les épaules vers la zone visée avant l'armé.$q$],
 array[$q$Prise d'élan trop proche du filet, qui limite l'extension.$q$,$q$Frapper toujours dans le même angle.$q$],
 array[$q$Ajoute un double bloc en face.$q$], array[$q$Passe plus haute et plus éloignée du filet.$q$],
 $q$Attaquer efficacement depuis la zone 2.$q$),

('063b1989-90c6-4445-8d42-c509265f24be','attaque_203','attaque',
 array[$q$lecture du bloc$q$,$q$attaque croisée$q$,$q$décision$q$], array[$q$attaque$q$,$q$bloc$q$,$q$lecture$q$,$q$avance$q$],
 'high',4,5,false,true,3,8,
 array[$q$Un bloqueur se place au filet et ferme un angle au hasard.$q$,$q$L'attaquant lit la position du bloc puis choisit croisé ou ligne.$q$,$q$5 séries de 6 attaques.$q$],
 array[$q$Regarde les mains du bloqueur juste avant l'armé, pas avant.$q$,$q$Garde les deux options ouvertes jusqu'au dernier moment.$q$,$q$Frappe dans l'espace libre plutôt que sur le bloc.$q$],
 array[$q$Frappe systématique au même endroit.$q$,$q$Décision prise avant même la passe.$q$],
 array[$q$Double bloc qui se déplace selon l'élan de l'attaquant.$q$], array[$q$Le bloqueur annonce l'angle qu'il ferme.$q$],
 $q$Choisir son angle d'attaque en fonction du bloc.$q$),

('fa7bf729-cce2-4aaa-a401-dd6ed240fcc7','attaque_204','attaque',
 array[$q$timing rapide$q$,$q$attaque rapide$q$,$q$coordination$q$], array[$q$attaque$q$,$q$rapide$q$,$q$central$q$,$q$timing$q$],
 'high',4,5,false,true,2,6,
 array[$q$Le passeur envoie des passes basses et proches de lui.$q$,$q$Le central déclenche son appel dès que le ballon quitte les mains du passeur.$q$,$q$5 séries de 6 attaques rapides.$q$],
 array[$q$Commence ton appel sur la trajectoire du ballon vers le passeur.$q$,$q$Cours vers le ballon, pas vers le filet.$q$,$q$Bras déjà armé au moment du saut.$q$],
 array[$q$Appel trop tardif qui fait arriver l'attaquant après le ballon.$q$,$q$Approche trop longue qui casse la vitesse.$q$],
 array[$q$Varie la zone de la passe rapide, devant puis derrière le passeur.$q$], array[$q$Passe un peu plus haute pour laisser le temps de l'appel.$q$],
 $q$Synchroniser l'appel avec une passe rapide.$q$),

('5abb4bc2-8357-44ef-bc31-1d0a0e8a7bc8','bloc_201','bloc',
 array[$q$déplacement latéral$q$,$q$bloc collectif$q$,$q$communication$q$], array[$q$bloc$q$,$q$deplacement$q$,$q$collectif$q$,$q$lateral$q$],
 'high',4,4,false,false,2,6,
 array[$q$Deux bloqueurs se placent au filet, le central part du centre.$q$,$q$Le central coulisse en pas chassés puis en pas croisé et saute avec l'ailier.$q$,$q$4 séries de 6 déplacements suivis d'un saut.$q$],
 array[$q$Communique à voix haute pour synchroniser l'appel de saut.$q$,$q$Termine ton déplacement par un appui d'arrêt avant de sauter.$q$,$q$Les deux blocs forment un mur sans espace entre les mains.$q$],
 array[$q$Pas croisé trop long qui déséquilibre le saut.$q$,$q$Saut désynchronisé entre les deux bloqueurs.$q$],
 array[$q$Ajoute un attaquant réel qui choisit son côté.$q$], array[$q$Réduis la distance de coulissage.$q$],
 $q$Former un double bloc fermé après un déplacement.$q$),

('422b2b9e-9bd1-4d8c-9910-6e44a195a8e4','bloc_202','bloc',
 array[$q$placement des mains$q$,$q$timing$q$,$q$bloc individuel$q$], array[$q$bloc$q$,$q$mains$q$,$q$timing$q$,$q$debutant$q$],
 'medium',3,2,false,false,2,4,
 array[$q$Un partenaire simule une attaque au filet.$q$,$q$Le bloqueur saute et pénètre les mains au-dessus du filet, doigts écartés.$q$,$q$4 séries de 8 sauts.$q$],
 array[$q$Les mains passent le filet juste après celles de l'attaquant.$q$,$q$Pousse les épaules vers l'avant sans toucher le filet.$q$,$q$Regarde le ballon, pas le filet.$q$],
 array[$q$Mains qui pénètrent trop tard le plan du filet.$q$,$q$Saut déclenché trop tôt.$q$],
 array[$q$L'attaquant varie le rythme et la zone de frappe.$q$], array[$q$Travaille le geste des mains sans saut.$q$],
 $q$Placer ses mains au bon moment au-dessus du filet.$q$),

('0a3b7998-8780-4635-ae2f-fcac9595df3c','deplacements_201','deplacements',
 array[$q$agilité$q$,$q$changement de direction$q$,$q$appuis$q$], array[$q$deplacements$q$,$q$agilite$q$,$q$parcours$q$,$q$vitesse$q$],
 'high',4,2,true,false,1,4,
 array[$q$Place quatre plots en T sur cinq mètres.$q$,$q$Sprint avant, déplacement latéral droite puis gauche, retour en recul, le tout chronométré.$q$,$q$4 séries avec une minute de récupération.$q$],
 array[$q$Reste bas sur tes appuis pendant tout le parcours.$q$,$q$Plante le pied extérieur pour repartir dans l'autre sens.$q$,$q$Garde les épaules dans l'axe du déplacement.$q$],
 array[$q$Redressement du buste dans les changements de direction.$q$,$q$Foulées trop longues qui freinent la relance.$q$],
 array[$q$Ajoute un signal visuel qui donne la direction au dernier moment.$q$], array[$q$Réduis la distance entre les plots.$q$],
 $q$Changer de direction sans perdre de vitesse.$q$),

('319be636-a5db-409d-8e46-95b920613ac1','reception_207','reception',
 array[$q$fondamentaux$q$,$q$polyvalence$q$,$q$contrôle$q$], array[$q$circuit$q$,$q$fondamentaux$q$,$q$debutant$q$,$q$polyvalence$q$],
 'medium',3,2,false,true,2,8,
 array[$q$Installe quatre ateliers : manchette, service, passe, déplacement.$q$,$q$Passe trois minutes sur chaque atelier, sans pause entre eux.$q$,$q$Un tour complet des quatre ateliers.$q$],
 array[$q$Priorise la qualité du geste à la quantité de répétitions.$q$,$q$Garde la même exigence sur le dernier atelier que sur le premier.$q$,$q$Compte tes réussites pour te situer d'une séance à l'autre.$q$],
 array[$q$Vouloir aller trop vite et bâcler la technique de base.$q$,$q$Passer plus de temps sur l'atelier préféré.$q$],
 array[$q$Ajoute un atelier attaque et allonge à quatre minutes.$q$], array[$q$Limite le circuit à deux ateliers.$q$],
 $q$Revoir les gestes de base dans une même séance.$q$),

('5ae38f06-dffe-43b5-99da-d7ea5c401307','lecture_jeu_201','lecture_jeu',
 array[$q$polyvalence$q$,$q$organisation$q$,$q$enchaînement$q$], array[$q$circuit$q$,$q$polyvalence$q$,$q$collectif$q$,$q$seance$q$],
 'high',4,3,false,true,6,12,
 array[$q$Installe six ateliers : réception, service, passe, attaque, bloc, défense.$q$,$q$Tourne toutes les trois minutes en changeant de poste à chaque atelier.$q$,$q$Un tour complet des six ateliers.$q$],
 array[$q$Change vraiment de poste à chaque atelier, même si ce n'est pas le tien.$q$,$q$Garde la même exigence technique sur chaque atelier.$q$,$q$Annonce le changement pour ne pas perdre de temps.$q$],
 array[$q$Rester sur le même atelier et perdre la polyvalence recherchée.$q$,$q$Baisser l'intensité sur les ateliers qu'on aime moins.$q$],
 array[$q$Réduis à deux minutes par atelier pour augmenter le rythme.$q$], array[$q$Limite le circuit à quatre ateliers.$q$],
 $q$Travailler les six fondamentaux dans une même séance.$q$),

('66caac7e-41ea-41cf-8e8e-756b0405b5e1','reception_201','reception',
 array[$q$enchaînement$q$,$q$régularité$q$,$q$replacement$q$], array[$q$enchainement$q$,$q$regularite$q$,$q$reception$q$,$q$passe$q$],
 'high',4,4,false,true,3,8,
 array[$q$Un lanceur envoie un ballon en réception.$q$,$q$Le joueur enchaîne réception, passe puis attaque sans pause entre les actions.$q$,$q$5 séries d'un enchaînement complet.$q$],
 array[$q$Reste sur tes appuis après chaque action, ne te relève pas complètement.$q$,$q$Replace-toi dès que le ballon quitte tes mains.$q$,$q$Cherche la régularité avant la puissance.$q$],
 array[$q$Précipitation entre les actions.$q$,$q$Perte de posture après la réception.$q$],
 array[$q$Enchaîne deux cycles complets sans pause.$q$], array[$q$Sépare les actions par deux secondes de pause.$q$],
 $q$Enchaîner les actions comme en match, sans temps mort.$q$),

('70d9a75d-3cc4-4e33-8824-2e83576bdd99','reception_202','reception',
 array[$q$déplacement latéral$q$,$q$réception$q$,$q$appuis$q$], array[$q$reception$q$,$q$deplacement$q$,$q$appuis$q$],
 'medium',3,3,false,true,2,6,
 array[$q$Le lanceur envoie des ballons décalés de deux à trois pas.$q$,$q$Le réceptionneur se déplace, se stabilise puis renvoie vers la cible.$q$,$q$4 séries de 10 réceptions.$q$],
 array[$q$Anticipe la trajectoire dès la frappe pour arriver stable avant le contact.$q$,$q$Termine ton déplacement par un appui d'arrêt.$q$,$q$Oriente ta plateforme vers la cible, pas vers le ballon.$q$],
 array[$q$Réception à l'arrêt sans s'être stabilisé.$q$,$q$Retard sur le placement des appuis.$q$],
 array[$q$Augmente la distance de déplacement à quatre ou cinq pas.$q$], array[$q$Envoie les ballons directement sur le joueur.$q$],
 $q$Rester stable en réception après un déplacement.$q$),

('5d8a502d-4f33-48ca-8648-822195aeb845','reception_203','reception',
 array[$q$contrôle$q$,$q$manchette$q$,$q$touche haute$q$], array[$q$controle$q$,$q$reception$q$,$q$solo$q$,$q$debutant$q$],
 'low',2,2,true,true,1,2,
 array[$q$Enchaîne une manchette puis une passe haute à toi-même.$q$,$q$Garde le ballon au-dessus de toi sans le laisser tomber.$q$,$q$3 séries de 15 enchaînements.$q$],
 array[$q$Laisse le ballon monter complètement avant le deuxième contact.$q$,$q$Reste sous le ballon, jambes fléchies.$q$,$q$Garde la plateforme stable, épaules devant.$q$],
 array[$q$Précipitation entre les deux contacts.$q$,$q$Ballon joué devant soi au lieu d'être joué au-dessus.$q$],
 array[$q$Recule d'un mètre à chaque enchaînement réussi.$q$], array[$q$Laisse le ballon rebondir une fois entre les contacts.$q$],
 $q$Contrôler deux contacts successifs sans perdre le ballon.$q$),

('e96723e6-0574-4904-ab42-0457ede90c3c','defense_201','defense',
 array[$q$lecture$q$,$q$anticipation$q$,$q$déplacement$q$], array[$q$defense$q$,$q$lecture$q$,$q$anticipation$q$],
 'medium',3,4,false,true,2,6,
 array[$q$Un attaquant frappe depuis le filet en variant les zones.$q$,$q$Le défenseur lit les épaules et le bras armé puis se déplace vers la zone anticipée.$q$,$q$4 séries de 8 lectures.$q$],
 array[$q$Fixe les épaules et le bras armé, pas le ballon.$q$,$q$Arrête tes appuis au moment de la frappe pour pouvoir partir des deux côtés.$q$,$q$Annonce à voix haute la zone que tu lis.$q$],
 array[$q$Regarder uniquement le ballon, ce qui retarde la lecture.$q$,$q$Partir avant la frappe et se faire prendre à contre-pied.$q$],
 array[$q$L'attaquant ajoute des feintes et des amortis.$q$], array[$q$L'attaquant annonce sa zone avant de frapper.$q$],
 $q$Anticiper la zone de frappe grâce au corps de l'attaquant.$q$),

('10fd714e-d968-4c68-8545-1dd2a7cb01bd','bloc_203','bloc',
 array[$q$lecture de passe$q$,$q$bloc individuel$q$,$q$timing$q$], array[$q$bloc$q$,$q$lecture$q$,$q$passe$q$,$q$exterieur$q$],
 'medium',3,4,false,true,3,8,
 array[$q$Le passeur adverse distribue vers l'aile ou au centre.$q$,$q$Le bloqueur extérieur déclenche son saut seulement après avoir lu la direction de la passe.$q$,$q$4 séries de 8 sauts.$q$],
 array[$q$Regarde la passe avant de regarder l'attaquant.$q$,$q$Reste en position basse tant que la passe n'est pas lue.$q$,$q$Ferme la ligne en priorité sur passe haute en aile.$q$],
 array[$q$Saut réflexe dès que l'attaquant arme.$q$,$q$Regard fixé sur l'attaquant, sans information sur la passe.$q$],
 array[$q$Le passeur ajoute des passes rapides au centre.$q$], array[$q$Le passeur annonce sa zone avant de toucher le ballon.$q$],
 $q$Déclencher son bloc à partir de la lecture de la passe.$q$),

('6d1ea812-d4da-4b51-b632-64328c2bad1f','reception_204','reception',
 array[$q$manchette$q$,$q$précision$q$,$q$plateforme$q$], array[$q$reception$q$,$q$manchette$q$,$q$cible$q$,$q$debutant$q$],
 'medium',2,2,false,true,2,4,
 array[$q$Marque deux ou trois zones cibles au sol.$q$,$q$Le lanceur envoie des ballons à la main, le réceptionneur les renvoie vers la cible annoncée.$q$,$q$3 séries de 20 ballons.$q$],
 array[$q$Garde les épaules devant les genoux et vise le passeur, pas le plafond.$q$,$q$Plateforme stable, bras tendus sans balancer.$q$,$q$Fléchis les jambes pour donner la trajectoire.$q$],
 array[$q$Bras qui montent trop haut au contact.$q$,$q$Recul au moment du contact.$q$],
 array[$q$Le lanceur envoie les ballons plus fort et plus loin.$q$], array[$q$Le lanceur envoie des ballons en cloche directement sur le joueur.$q$],
 $q$Renvoyer le ballon vers une cible précise en manchette.$q$),

('f8adf2d7-f89e-44c2-8978-3b94bfc14515','mobilite_201','mobilite',
 array[$q$mobilité articulaire$q$,$q$prévention$q$,$q$hanches$q$], array[$q$mobilite$q$,$q$prevention$q$,$q$chevilles$q$,$q$sans materiel$q$],
 'low',1,1,true,false,1,12,
 array[$q$Dix rotations de cheville par côté, lentement.$q$,$q$Dix fentes dynamiques par jambe puis dix cercles de hanches par côté.$q$,$q$Trois tours, avant chaque séance de saut.$q$],
 array[$q$Fais chaque mouvement lentement et en contrôle.$q$,$q$Cherche l'amplitude, pas la vitesse.$q$,$q$Respire régulièrement pendant les mouvements.$q$],
 array[$q$Mouvements trop rapides qui perdent l'intérêt de la mobilisation.$q$,$q$Amplitude réduite par manque d'attention.$q$],
 array[$q$Ajoute une mobilité de cheville en charge contre un mur.$q$], array[$q$Réduis à deux tours avec des amplitudes plus courtes.$q$],
 $q$Préparer chevilles et hanches avant les séances de saut.$q$),

('5d4bc272-b612-400d-a44f-51177a620c92','deplacements_202','deplacements',
 array[$q$déplacement latéral$q$,$q$vitesse$q$,$q$freinage$q$], array[$q$deplacements$q$,$q$vitesse$q$,$q$navette$q$,$q$plots$q$],
 'high',4,2,true,false,1,6,
 array[$q$Place deux plots espacés de six mètres.$q$,$q$Enchaîne six allers-retours en pas chassés, sans croiser les appuis.$q$,$q$5 séries avec 30 secondes de récupération.$q$],
 array[$q$Petits appuis rapides plutôt que grandes foulées.$q$,$q$Touche le plot avec la main pour rester bas.$q$,$q$Garde le buste légèrement penché vers l'avant.$q$],
 array[$q$Redressement trop tôt en fin de course.$q$,$q$Foulées trop longues dans les changements de direction.$q$],
 array[$q$Chronomètre chaque série et cherche à tenir le même temps.$q$], array[$q$Réduis la distance à quatre mètres.$q$],
 $q$Gagner en vitesse sur les déplacements latéraux.$q$),

('b7cf5af2-702a-48b1-98a5-f59b020e9cb9','passe_201','passe',
 array[$q$touche haute$q$,$q$précision$q$,$q$placement des mains$q$], array[$q$passe$q$,$q$precision$q$,$q$cible$q$,$q$debutant$q$],
 'medium',2,3,false,true,2,4,
 array[$q$Place une cible en zone 4 puis une en zone 2.$q$,$q$Le joueur enchaîne des passes hautes vers la cible annoncée.$q$,$q$4 séries de 15 passes.$q$],
 array[$q$Garde les mains en forme de fenêtre au-dessus du front avant le contact.$q$,$q$Finis le geste en poussant vers la cible.$q$,$q$Place-toi sous le ballon, pas à côté.$q$],
 array[$q$Passe jouée trop en avant du corps.$q$,$q$Mains qui se referment trop tôt.$q$],
 array[$q$Alterne les deux cibles au signal du partenaire.$q$], array[$q$Rapproche la cible et joue après un rebond au sol.$q$],
 $q$Envoyer une passe haute précise vers une cible.$q$),

('bb234018-b88f-4139-985a-dfd6564bbd8c','passe_202','passe',
 array[$q$passe arrière$q$,$q$précision$q$,$q$dissimulation$q$], array[$q$passe$q$,$q$arriere$q$,$q$precision$q$,$q$passeur$q$],
 'medium',3,4,false,true,2,4,
 array[$q$Place une cible en zone 2, le passeur tourne le dos à cette zone.$q$,$q$Le passeur envoie des passes arrière sans se retourner.$q$,$q$4 séries de 12 passes.$q$],
 array[$q$Garde les épaules face au filet, seuls les bras et les poignets envoient le ballon en arrière.$q$,$q$Joue le ballon au-dessus du front, pas derrière la tête.$q$,$q$Termine en extension vers le haut.$q$],
 array[$q$Rotation du buste vers l'arrière, qui rend la passe prévisible.$q$,$q$Ballon joué trop bas, derrière la tête.$q$],
 array[$q$Alterne passe avant et passe arrière au signal.$q$], array[$q$Réduis la distance de la cible.$q$],
 $q$Envoyer une passe arrière précise sans se retourner.$q$),

('66a3e62a-3743-4d70-8355-277b8e3a0f19','detente_201','detente',
 array[$q$pliométrie$q$,$q$puissance réactive$q$,$q$temps de contact$q$], array[$q$detente$q$,$q$pliometrie$q$,$q$puissance$q$,$q$plyobox$q$],
 'high',5,3,true,false,1,6,
 array[$q$Descends d'une box de 30 à 40 cm en te laissant tomber, sans sauter.$q$,$q$Dès le contact au sol, rebondis le plus haut possible.$q$,$q$5 séries de 5 sauts, deux minutes de récupération entre les séries.$q$],
 array[$q$Pense sol brûlant : minimise le temps de contact au sol.$q$,$q$Reçois sur l'avant du pied, genoux souples mais actifs.$q$,$q$Arrête la série dès que la qualité du rebond baisse.$q$],
 array[$q$Temps de contact au sol trop long.$q$,$q$Réception genoux verrouillés.$q$],
 array[$q$Augmente légèrement la hauteur de la box.$q$], array[$q$Travaille des sauts verticaux simples, sans contrebas.$q$],
 $q$Développer la puissance réactive des jambes.$q$),

('d61710a1-9373-48fa-9dac-9672726f7b01','defense_202','defense',
 array[$q$plongeon$q$,$q$roulade$q$,$q$technique au sol$q$], array[$q$defense$q$,$q$plongeon$q$,$q$roulade$q$,$q$securite$q$],
 'high',4,4,true,false,1,4,
 array[$q$Place-toi en position basse au centre du tapis.$q$,$q$Plonge latéralement en amortissant sur le côté du corps puis enchaîne une roulade.$q$,$q$4 séries de 6 plongeons, trois de chaque côté.$q$],
 array[$q$Enchaîne toujours avec une roulade, n'amortis jamais sur les coudes.$q$,$q$Garde le menton rentré pendant la roulade.$q$,$q$Commence lentement, la vitesse vient après la technique.$q$],
 array[$q$Réception du poids du corps sur les bras tendus.$q$,$q$Roulade incomplète qui laisse le joueur bloqué au sol.$q$],
 array[$q$Ajoute un ballon à sauver envoyé par un partenaire.$q$], array[$q$Travaille la roulade depuis la position accroupie, sans plongeon.$q$],
 $q$Sauver un ballon bas sans se blesser.$q$),

('87481dc3-7d33-4efb-9dd7-ba9ec7719666','lecture_jeu_202','lecture_jeu',
 array[$q$situation de jeu$q$,$q$gestion de pression$q$,$q$organisation collective$q$], array[$q$competition$q$,$q$match$q$,$q$collectif$q$,$q$pression$q$],
 'high',4,5,false,true,6,12,
 array[$q$Formez deux équipes complètes avec rotation des six postes.$q$,$q$Jouez des points à thème : service, réception puis attaque, en annonçant le score à voix haute.$q$,$q$Deux manches de quinze points.$q$],
 array[$q$Simule la pression du match : annonce le score à voix haute.$q$,$q$Garde tes rituels d'avant-service comme en compétition.$q$,$q$Corrige entre les points, pas pendant.$q$],
 array[$q$Intensité trop faible par rapport au rythme réel de match.$q$,$q$Rotation négligée, chacun reste à son poste préféré.$q$],
 array[$q$Joue des points en partant d'un score défavorable.$q$], array[$q$Joue des points sans service, ballon lancé par le coach.$q$],
 $q$Retrouver le rythme et la pression du match.$q$),

('e535da57-87db-49fa-82df-32b2a88d9f45','deplacements_203','deplacements',
 array[$q$vitesse de réaction$q$,$q$démarrage$q$,$q$premier appui$q$], array[$q$deplacements$q$,$q$reaction$q$,$q$signal$q$,$q$vitesse$q$],
 'high',4,2,false,false,2,6,
 array[$q$Place-toi en position d'attente, un partenaire face à toi.$q$,$q$Dès qu'il lève le bras, sprinte trois mètres dans la direction indiquée.$q$,$q$5 séries de 5 sprints.$q$],
 array[$q$Demande à ton partenaire de varier le délai avant le signal.$q$,$q$Pousse fort sur le premier appui plutôt que de multiplier les petits pas.$q$,$q$Reste sur l'avant des pieds en attente.$q$],
 array[$q$Anticipation du signal au lieu d'une vraie réaction.$q$,$q$Premier appui dans le mauvais sens.$q$],
 array[$q$Le partenaire indique la direction au dernier moment.$q$], array[$q$Allonge le délai avant le signal et raccourcis la distance.$q$],
 $q$Réduire le temps entre le signal et le premier appui.$q$),

('ff371f0f-f4c6-4378-9c88-e0488b8cb0ea','reception_205','reception',
 array[$q$réception de service$q$,$q$déplacement$q$,$q$orientation$q$], array[$q$reception$q$,$q$diagonale$q$,$q$deplacement$q$,$q$avance$q$],
 'high',4,4,false,true,2,6,
 array[$q$Le lanceur envoie des ballons en diagonale, alternativement vers la zone 1 et la zone 5.$q$,$q$Le réceptionneur se déplace et renvoie vers la zone de passe.$q$,$q$4 séries de 8 réceptions.$q$],
 array[$q$Ouvre tes appuis vers l'endroit où tu veux envoyer le ballon.$q$,$q$Pars dès que la main du lanceur touche le ballon.$q$,$q$Renvoie haut pour laisser le temps au passeur.$q$],
 array[$q$Appuis parallèles au filet au lieu d'être orientés vers la trajectoire.$q$,$q$Bras qui suivent le ballon au lieu de rester fixes.$q$],
 array[$q$Le lanceur sert réellement depuis le fond du terrain.$q$], array[$q$Réduis l'écart entre les deux zones.$q$],
 $q$Couvrir la largeur du terrain en réception.$q$),

('dbe15433-fa3a-4107-95d4-607199087a2e','reception_206','reception',
 array[$q$réception de service$q$,$q$réflexes$q$,$q$lecture de trajectoire$q$], array[$q$reception$q$,$q$pression$q$,$q$service$q$,$q$smashe$q$],
 'high',4,5,false,true,2,6,
 array[$q$Le serveur frappe des services puissants depuis le fond.$q$,$q$Le réceptionneur couvre alternativement les zones 1, 5 et 6.$q$,$q$5 séries de 5 réceptions.$q$],
 array[$q$Fixe le point de contact du serveur avec le ballon, pas le serveur.$q$,$q$Bras souples mais plateforme ferme au contact.$q$,$q$Recule d'un pas si le service part très tendu.$q$],
 array[$q$Bras trop mous ou trop rigides.$q$,$q$Mauvaise lecture de la trajectoire au départ.$q$],
 array[$q$Le serveur alterne services smashés et flottants.$q$], array[$q$Le serveur sert depuis les trois mètres, moins fort.$q$],
 $q$Rester efficace en réception sur service puissant.$q$),

('8066e561-00af-4cc1-9374-c7549fcd13c1','renforcement_201','renforcement',
 array[$q$force$q$,$q$gainage$q$,$q$endurance musculaire$q$], array[$q$renforcement$q$,$q$circuit$q$,$q$sans materiel$q$,$q$maison$q$],
 'high',4,1,true,false,1,12,
 array[$q$Enchaîne 15 squats, 10 pompes, 30 secondes de gainage et 10 fentes par jambe.$q$,$q$Récupère 30 secondes entre les tours.$q$,$q$4 tours du circuit.$q$],
 array[$q$Priorise une exécution propre plutôt que la vitesse.$q$,$q$Garde le dos droit et le ventre gainé sur chaque mouvement.$q$,$q$Arrête une série si la posture se dégrade.$q$],
 array[$q$Enchaîner les tours sans respecter le temps de repos.$q$,$q$Dégradation rapide de la forme d'exécution.$q$],
 array[$q$Ajoute un cinquième tour ou augmente les répétitions de 20 %.$q$], array[$q$Fais trois tours, avec les pompes sur les genoux.$q$],
 $q$Renforcer le corps sans matériel, en complément du travail technique.$q$),

('4aa41dc2-0dd4-44d2-9391-939dbb89e2dc','service_201','service',
 array[$q$service flottant$q$,$q$contact sec$q$,$q$précision$q$], array[$q$service$q$,$q$flottant$q$,$q$precision$q$,$q$solo$q$],
 'medium',3,4,true,true,1,6,
 array[$q$Place-toi derrière la ligne de fond, ballon devant l'épaule de frappe.$q$,$q$Frappe sec au centre du ballon, sans accompagner le geste.$q$,$q$4 séries de 8 services.$q$],
 array[$q$Coupe net ton geste juste après le contact.$q$,$q$Lancer de balle bas et devant, sans rotation.$q$,$q$Frappe avec la paume ferme, poignet bloqué.$q$],
 array[$q$Bras qui accompagne trop le ballon après le contact.$q$,$q$Lancer de balle trop haut, qui fait tourner le ballon.$q$],
 array[$q$Vise successivement les zones 1, 6 puis 5.$q$], array[$q$Sers depuis la ligne des trois mètres.$q$],
 $q$Produire un service flottant régulier.$q$),

('4747ed4d-5ed3-4701-9d40-caac5fc96973','service_202','service',
 array[$q$service smashé$q$,$q$puissance$q$,$q$armé$q$], array[$q$service$q$,$q$smashe$q$,$q$puissance$q$,$q$avance$q$],
 'high',4,5,true,true,1,6,
 array[$q$Lance le ballon haut et devant, puis enchaîne deux à trois pas d'élan.$q$,$q$Frappe le ballon au point le plus haut en visant la profondeur.$q$,$q$5 séries de 6 services.$q$],
 array[$q$Travaille l'armé complet avant de chercher la puissance maximale.$q$,$q$Garde le même lancer à chaque service.$q$,$q$Termine le geste vers l'avant, sans casser le poignet trop tôt.$q$],
 array[$q$Armé du bras trop tardif.$q$,$q$Manque d'extension au moment du contact.$q$],
 array[$q$Ajoute une cible en fond de terrain à atteindre une fois sur deux.$q$], array[$q$Sers à 70 % de puissance en cherchant d'abord la régularité.$q$],
 $q$Gagner en puissance sans perdre la régularité au service.$q$),

('9e341e80-d052-4a23-b82e-d4c9437df5ff','service_203','service',
 array[$q$service$q$,$q$précision$q$,$q$routine$q$], array[$q$service$q$,$q$cible$q$,$q$precision$q$,$q$debutant$q$],
 'medium',3,3,true,true,1,6,
 array[$q$Marque quatre zones dans le terrain adverse.$q$,$q$Sers successivement vers chaque zone annoncée à voix haute.$q$,$q$4 séries de 8 services.$q$],
 array[$q$Standardise ton lancer de balle : même hauteur, même point à chaque fois.$q$,$q$Garde la même routine avant chaque service.$q$,$q$Vise une zone large avant de viser un point précis.$q$],
 array[$q$Lancer de balle irrégulier.$q$,$q$Tempo précipité entre le lancer et la frappe.$q$],
 array[$q$Réduis la taille des zones cibles.$q$], array[$q$Sers depuis la ligne des trois mètres vers des zones larges.$q$],
 $q$Servir dans la zone choisie, pas seulement dans le terrain.$q$),

('2a3920e5-0e89-4bc8-afb3-905b9fd0b740','defense_203','defense',
 array[$q$transition$q$,$q$replacement$q$,$q$posture basse$q$], array[$q$defense$q$,$q$bloc$q$,$q$transition$q$,$q$enchainement$q$],
 'high',4,4,false,true,2,6,
 array[$q$Saute au bloc sur une attaque simulée.$q$,$q$Dès la retombée, recule en position basse et défends le ballon suivant.$q$,$q$4 séries de 6 enchaînements.$q$],
 array[$q$Pense bloc puis recul comme un seul geste continu.$q$,$q$Retombe face au terrain, pas face au filet.$q$,$q$Reprends une position basse avant le contact.$q$],
 array[$q$Temps de réaction trop long après la retombée.$q$,$q$Rester debout au moment de la défense.$q$],
 array[$q$Le partenaire envoie le ballon de défense plus tôt.$q$], array[$q$Laisse une seconde de pause entre le bloc et la défense.$q$],
 $q$Enchaîner bloc et défense sans temps mort.$q$),

('ccb39820-b13c-4718-8aaf-a53de787d283','bloc_204','bloc',
 array[$q$bloc collectif$q$,$q$communication$q$,$q$déplacement au filet$q$], array[$q$bloc$q$,$q$collectif$q$,$q$triple$q$,$q$avance$q$],
 'high',4,5,false,false,3,8,
 array[$q$Trois bloqueurs se placent au filet, l'extérieur annonce la direction à fermer.$q$,$q$Le central coulisse et ferme avec l'ailier désigné, le troisième couvre le reste.$q$,$q$4 séries de 6 sauts à trois.$q$],
 array[$q$Le central donne la direction à voix haute avant le saut : dehors ou ligne.$q$,$q$Sautez ensemble, sans espace entre les mains.$q$,$q$Terminez le geste en poussant les épaules vers l'avant.$q$],
 array[$q$Bloqueurs qui sautent sans se synchroniser sur l'appel.$q$,$q$Espace laissé entre deux blocs.$q$],
 array[$q$Ajoute un attaquant qui choisit sa zone au dernier moment.$q$], array[$q$Travaille à deux bloqueurs avant de passer à trois.$q$],
 $q$Fermer une large zone avec un bloc à trois.$q$)
) as v(id, slug, category, skills, tags, intensity, physical_load, technical_load,
       solo_compatible, ball_required, players_min, players_max,
       instruction_steps, coaching_points, common_mistakes_list,
       progressions, regressions, objective_statement)
where e.id = v.id;
